config/routes.rb
Rideon::Application.routes.draw do
  resources :authentications

  devise_for :users, controllers: {registrations: "registrations"} #:skip => [:sessions] do

  resources :providers
  resources :members
  resources :routes
  match "auth/twitter/callback" => "authentications#twitter"
  match "auth/facebook/callback" => "authentications#facebook"

  resources :ratings

  root to: 'authentications#home'
  resources :users, :path => 'user'

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/register" => "members#new"
  end

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :provider, :uid, :token, :token_secret, :user_id, :avatar
  belongs_to :user
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      authentication.provider = auth.provider
      authentication.uid = auth.uid
      authentication.token = auth.token
      authentication.token_secret = auth.token_secret
    end
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  #load_and_authorize_resource
  #check_authorization
  def index
    @authentications = Authentication.all
  end

  def twitter
    omni = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omni['provider'], omni['uid'])
    #raise omni.to_yaml
    
    if authentication
      flash[:notice] = "Logged in Successfully"
      #session[:user_id] = authentication.user_id
      sign_in_and_redirect User.find(authentication.user_id)
    elsif current_user
      token = omni['credentials'].token
      token_secret = omni['credentials'].secret
      
      current_user.authentications.create!(:provider => omni['provider'], :uid => omni['uid'], :token => token, :token_secret => token_secret)
      flash[:notice] = "Authentication successful."
      sign_in_and_redirect current_user
    else
      user = User.new
      user.provider = omni.provider
      user.uid = omni.uid

      user.apply_omniauth(omni)
      
      if user.save
        flash[:notice] = "Logged in."
        sign_in_and_redirect User.find(user.id)             
      else
        session[:omniauth] = omni.except('extra')
        redirect_to new_user_registration_path
      end
    end 
  end

  def facebook
    omni = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omni['provider'], omni['uid'])

    if authentication
      flash[:notice] = "Logged in Successfully"
      sign_in_and_redirect User.find(authentication.user_id)
    elsif current_user
      token = omni['credentials'].token
      token_secret = ""
      
      current_user.authentications.create!(:provider => omni['provider'], :uid => omni['uid'], :token => token, :token_secret => token_secret)
      
      flash[:notice] = "Authentication successful."
      sign_in_and_redirect current_user
    else
      user = User.new
      user.provider = omni.provider
      user.uid = omni.uid
      user.email = omni['extra']['raw_info'].email 
      user.roles= ['member'] # user is a member by defalt of logging using facebook account
      # Create a New Member association (first_name, last_name, dob)
      member = Member.new()
      member.first_name = omni.info.first_name
      member.last_name = omni.info.last_name
      user.avatar = open(omni.info.image)
      member.dob = omni.extra.raw_info.birthday
      user.profile = member
      user.apply_omniauth(omni)

      if user.save
        flash[:notice] = "Logged in."
        sign_in_and_redirect User.find(user.id)             
      else
        session[:omniauth] = omni.except('extra')
        redirect_to new_user_registration_path # might be the case that the email has been used! (login with twitter before?)
      end
    end
  end

 def create
    raise request.env["omniauth.auth"].to_yaml
    @authentication = Authentication.new(params[:authentication])
    if @authentication.save
      redirect_to authentications_url, :notice => "Successfully created authentication."
    else
      render :action => 'new'
    end
  end

  def destroy
    @authentication = Authentication.find(params[:id])
    @authentication.destroy
    redirect_to authentications_url, :notice => "Successfully destroyed authentication."
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/home.html.erb
<!-- THIS WILL BE THE HOME PAGE for LOGIN USER -->

<% if user_signed_in? %>
<!-- redirect to current route pages -->
Logged in as <strong><%= current_user.email %></strong>.

<% else %>
<center>
	<%= link_to "Sign up as provider", new_provider_path %>  | <%= link_to "Sign up as user", new_member_path %> |
	<%= link_to "Login", new_user_session_path %>
</center>
<% end %>

app/views/authentications/index.html.erb
<% provide(:title, 'Othentikeysins') %>

<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <%= image_tag "#{authentication.provider}_32.png", :size => "32x32" %>
          <div class="uid"><%= authentication.uid %></div>
          <%= link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>

<a href="/users/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<a href="/users/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>
<div class="clear"></div>