config/routes.rb
Rideon::Application.routes.draw do
  resources :authentications

  devise_for :users, controllers: {registrations: "registrations"} #:skip => [:sessions] do

  resources :providers
  resources :members
  resources :routes
  match "auth/twitter/callback" => "authentications#twitter"
  match "auth/facebook/callback" => "authentications#facebook"

  resources :ratings

  root to: 'authentications#home'
  resources :users, :path => 'user'

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
    get "/register" => "members#new"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "rideon" %></title>
    <%= csrf_meta_tags %>
    <!-- Include google map api -->
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyCrdEne8v1dZN_0gX7G43DAo06WmIIKNyA&sensor=false" %>
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body onload="initialize()">


      <div class="container" id="nav-wrapper">
        <!-- navbar will change to "navbar-fixed-top" as user scroll down the pages-->
        <div class="navbar" id="nav">
          <div class="navbar-inner">
              <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </a>
              <a class="brand" href="#"><%= image_tag("header.png", :size => "50X50") %></a>
              <div class="nav-collapse">
                <ul class="nav">
                  <li><%= link_to "Standard", "/path1"  %></li>
                  <li><%= link_to "Comfort", "/path2"  %></li>
                  <li><%= link_to "Luxuary", "/path3"  %></li>
                </ul>

                <ul class="nav pull-right">              
                  <form class="navbar-search pull-left input-append">
                    <input name="main_search" type="text" class="search-query input-medium" placeholder="Search">
                  </form>   
                    <li class="divider-vertical"></li>
                    <!-- If user has logged in-->
                    <% if user_signed_in? %>
                    <li class="profile">
                      <ul class="nav">
                        <li>
                          <a href="/">
                            <%= image_tag(current_user.avatar.url(:thumb)) %>
                            <!-- Display name based on profile type -->
                            <%= current_user.profile.first_name if current_user.profile_type == "Member" %>
                            <%= current_user.profile.name if current_user.profile_type == "Provider" %>
                            <%= current_user.profile.name if current_user.profile_type == "Admin" %>
                          </a>
                        </li>
                      </ul>
                    </li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="icon-user icon-large icon-border"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="#">Action</a></li>
                    </ul>
                    </li>
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="icon-cogs icon-large icon-border"></b></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
                      <li><%= link_to "Privacy Settings", edit_user_registration_path  %></li>
                      <li><%= link_to 'Authentications', authentications_path %></li>
                      <li class="divider"></li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                    </ul>
                    </li>
                    <!-- If user has not log in-->
                    <% else %>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i>login <b class="caret"></b></a>
                        <ul class="dropdown-menu" style="padding-left:10px;padding-right:10px;padding-top:20px;">
                          <!-- Login form here -->
                              <%= form_for :user, :url => session_path("user") do |f| %>
                              <%= f.email_field :email, :autofocus => true, :placeholder =>"Your Email", :class =>"span3" %>
                              <%= f.password_field :password, :placeholder =>"New Password", :class =>"span3" %>
                                <% if devise_mapping.rememberable? -%>
                                    <label class="checkbox">
                                      <%= f.check_box :remember_me %> Remember me
                                      </label>
                                <% end -%>
                              <%= f.submit "Sign in", :class =>"btn btn-block btn-info" %>
                              <% end %>
                              <li class="divider"></li>
                              <center>
                              <%= link_to "Login with <i class=icon-facebook></i>".html_safe, "/auth/facebook", :class=>"btn btn-default" %>
                              <%= link_to "Login with <i class=icon-twitter></i>".html_safe, "/auth/twitter", :class=>"btn btn-default" %>
                              </center>
                          </ul>
                      </li>
                    <% end %> 
                </ul>

              </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>


      <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <!-- put <%= bootstrap_flash%> into individual views -->
            
            <%= yield %>
        </div>
      </div>
      </div> <!-- /container -->

      <footer>
        <div class="container">
        <p>&copy; 2013 rideon.sg. All rights reserved.</p>
        </div>
      </footer> <!-- /footer -->


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body> <!-- /body -->
</html> <!-- /html -->